name: Daily Code Push

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)

jobs:
  push_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "$(date) - Auto commit" >> auto_update.txt

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Automated commit - $(date)" || echo "No changes to commit"
          git push
